env:
  global:
    - CC_TEST_REPORTER_ID=9bb73c4aa1ef0196751fae6eb820280a7fb72b11a226e6a9a44092ec712ef355
language: "java"
install: "mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V"
script:
  - mvn clean install jacoco:report -Dmaven.javadoc.skip=true
  - ls -laR
group: "stable"
dist: "trusty"
os: "linux"
jdk:
  - oraclejdk8
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build -t jacoco --exit-code $TRAVIS_TEST_RESULT
