// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package org.flippers.messages;

public final class MessageProtos {
  private MessageProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:messages.Message)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.messages.Message.MessageType type = 1;</code>
     */
    int getTypeValue();
    /**
     * <code>.messages.Message.MessageType type = 1;</code>
     */
    org.flippers.messages.MessageProtos.Message.MessageType getType();

    /**
     * <code>string sequenceNumber = 3;</code>
     */
    java.lang.String getSequenceNumber();
    /**
     * <code>string sequenceNumber = 3;</code>
     */
    com.google.protobuf.ByteString
        getSequenceNumberBytes();

    /**
     * <code>.messages.NodeInfo sender = 4;</code>
     */
    boolean hasSender();
    /**
     * <code>.messages.NodeInfo sender = 4;</code>
     */
    org.flippers.messages.MessageProtos.NodeInfo getSender();
    /**
     * <code>.messages.NodeInfo sender = 4;</code>
     */
    org.flippers.messages.MessageProtos.NodeInfoOrBuilder getSenderOrBuilder();

    /**
     * <code>repeated .messages.NodeInfo nodesInfo = 5;</code>
     */
    java.util.List<org.flippers.messages.MessageProtos.NodeInfo> 
        getNodesInfoList();
    /**
     * <code>repeated .messages.NodeInfo nodesInfo = 5;</code>
     */
    org.flippers.messages.MessageProtos.NodeInfo getNodesInfo(int index);
    /**
     * <code>repeated .messages.NodeInfo nodesInfo = 5;</code>
     */
    int getNodesInfoCount();
    /**
     * <code>repeated .messages.NodeInfo nodesInfo = 5;</code>
     */
    java.util.List<? extends org.flippers.messages.MessageProtos.NodeInfoOrBuilder> 
        getNodesInfoOrBuilderList();
    /**
     * <code>repeated .messages.NodeInfo nodesInfo = 5;</code>
     */
    org.flippers.messages.MessageProtos.NodeInfoOrBuilder getNodesInfoOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code messages.Message}
   */
  public  static final class Message extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:messages.Message)
      MessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Message.newBuilder() to construct.
    private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Message() {
      type_ = 0;
      sequenceNumber_ = "";
      nodesInfo_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Message(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              sequenceNumber_ = s;
              break;
            }
            case 34: {
              org.flippers.messages.MessageProtos.NodeInfo.Builder subBuilder = null;
              if (sender_ != null) {
                subBuilder = sender_.toBuilder();
              }
              sender_ = input.readMessage(org.flippers.messages.MessageProtos.NodeInfo.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(sender_);
                sender_ = subBuilder.buildPartial();
              }

              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                nodesInfo_ = new java.util.ArrayList<org.flippers.messages.MessageProtos.NodeInfo>();
                mutable_bitField0_ |= 0x00000008;
              }
              nodesInfo_.add(
                  input.readMessage(org.flippers.messages.MessageProtos.NodeInfo.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          nodesInfo_ = java.util.Collections.unmodifiableList(nodesInfo_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.flippers.messages.MessageProtos.internal_static_messages_Message_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.flippers.messages.MessageProtos.internal_static_messages_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.flippers.messages.MessageProtos.Message.class, org.flippers.messages.MessageProtos.Message.Builder.class);
    }

    /**
     * Protobuf enum {@code messages.Message.MessageType}
     */
    public enum MessageType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>PING = 0;</code>
       */
      PING(0),
      /**
       * <code>ACK = 1;</code>
       */
      ACK(1),
      /**
       * <code>PING_NODE = 2;</code>
       */
      PING_NODE(2),
      /**
       * <code>JOIN = 3;</code>
       */
      JOIN(3),
      /**
       * <code>LEAVE = 4;</code>
       */
      LEAVE(4),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>PING = 0;</code>
       */
      public static final int PING_VALUE = 0;
      /**
       * <code>ACK = 1;</code>
       */
      public static final int ACK_VALUE = 1;
      /**
       * <code>PING_NODE = 2;</code>
       */
      public static final int PING_NODE_VALUE = 2;
      /**
       * <code>JOIN = 3;</code>
       */
      public static final int JOIN_VALUE = 3;
      /**
       * <code>LEAVE = 4;</code>
       */
      public static final int LEAVE_VALUE = 4;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static MessageType valueOf(int value) {
        return forNumber(value);
      }

      public static MessageType forNumber(int value) {
        switch (value) {
          case 0: return PING;
          case 1: return ACK;
          case 2: return PING_NODE;
          case 3: return JOIN;
          case 4: return LEAVE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          MessageType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
              public MessageType findValueByNumber(int number) {
                return MessageType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.flippers.messages.MessageProtos.Message.getDescriptor().getEnumTypes().get(0);
      }

      private static final MessageType[] VALUES = values();

      public static MessageType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private MessageType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:messages.Message.MessageType)
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>.messages.Message.MessageType type = 1;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.messages.Message.MessageType type = 1;</code>
     */
    public org.flippers.messages.MessageProtos.Message.MessageType getType() {
      @SuppressWarnings("deprecation")
      org.flippers.messages.MessageProtos.Message.MessageType result = org.flippers.messages.MessageProtos.Message.MessageType.valueOf(type_);
      return result == null ? org.flippers.messages.MessageProtos.Message.MessageType.UNRECOGNIZED : result;
    }

    public static final int SEQUENCENUMBER_FIELD_NUMBER = 3;
    private volatile java.lang.Object sequenceNumber_;
    /**
     * <code>string sequenceNumber = 3;</code>
     */
    public java.lang.String getSequenceNumber() {
      java.lang.Object ref = sequenceNumber_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sequenceNumber_ = s;
        return s;
      }
    }
    /**
     * <code>string sequenceNumber = 3;</code>
     */
    public com.google.protobuf.ByteString
        getSequenceNumberBytes() {
      java.lang.Object ref = sequenceNumber_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sequenceNumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SENDER_FIELD_NUMBER = 4;
    private org.flippers.messages.MessageProtos.NodeInfo sender_;
    /**
     * <code>.messages.NodeInfo sender = 4;</code>
     */
    public boolean hasSender() {
      return sender_ != null;
    }
    /**
     * <code>.messages.NodeInfo sender = 4;</code>
     */
    public org.flippers.messages.MessageProtos.NodeInfo getSender() {
      return sender_ == null ? org.flippers.messages.MessageProtos.NodeInfo.getDefaultInstance() : sender_;
    }
    /**
     * <code>.messages.NodeInfo sender = 4;</code>
     */
    public org.flippers.messages.MessageProtos.NodeInfoOrBuilder getSenderOrBuilder() {
      return getSender();
    }

    public static final int NODESINFO_FIELD_NUMBER = 5;
    private java.util.List<org.flippers.messages.MessageProtos.NodeInfo> nodesInfo_;
    /**
     * <code>repeated .messages.NodeInfo nodesInfo = 5;</code>
     */
    public java.util.List<org.flippers.messages.MessageProtos.NodeInfo> getNodesInfoList() {
      return nodesInfo_;
    }
    /**
     * <code>repeated .messages.NodeInfo nodesInfo = 5;</code>
     */
    public java.util.List<? extends org.flippers.messages.MessageProtos.NodeInfoOrBuilder> 
        getNodesInfoOrBuilderList() {
      return nodesInfo_;
    }
    /**
     * <code>repeated .messages.NodeInfo nodesInfo = 5;</code>
     */
    public int getNodesInfoCount() {
      return nodesInfo_.size();
    }
    /**
     * <code>repeated .messages.NodeInfo nodesInfo = 5;</code>
     */
    public org.flippers.messages.MessageProtos.NodeInfo getNodesInfo(int index) {
      return nodesInfo_.get(index);
    }
    /**
     * <code>repeated .messages.NodeInfo nodesInfo = 5;</code>
     */
    public org.flippers.messages.MessageProtos.NodeInfoOrBuilder getNodesInfoOrBuilder(
        int index) {
      return nodesInfo_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != org.flippers.messages.MessageProtos.Message.MessageType.PING.getNumber()) {
        output.writeEnum(1, type_);
      }
      if (!getSequenceNumberBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, sequenceNumber_);
      }
      if (sender_ != null) {
        output.writeMessage(4, getSender());
      }
      for (int i = 0; i < nodesInfo_.size(); i++) {
        output.writeMessage(5, nodesInfo_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != org.flippers.messages.MessageProtos.Message.MessageType.PING.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      if (!getSequenceNumberBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, sequenceNumber_);
      }
      if (sender_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getSender());
      }
      for (int i = 0; i < nodesInfo_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, nodesInfo_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.flippers.messages.MessageProtos.Message)) {
        return super.equals(obj);
      }
      org.flippers.messages.MessageProtos.Message other = (org.flippers.messages.MessageProtos.Message) obj;

      boolean result = true;
      result = result && type_ == other.type_;
      result = result && getSequenceNumber()
          .equals(other.getSequenceNumber());
      result = result && (hasSender() == other.hasSender());
      if (hasSender()) {
        result = result && getSender()
            .equals(other.getSender());
      }
      result = result && getNodesInfoList()
          .equals(other.getNodesInfoList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (37 * hash) + SEQUENCENUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getSequenceNumber().hashCode();
      if (hasSender()) {
        hash = (37 * hash) + SENDER_FIELD_NUMBER;
        hash = (53 * hash) + getSender().hashCode();
      }
      if (getNodesInfoCount() > 0) {
        hash = (37 * hash) + NODESINFO_FIELD_NUMBER;
        hash = (53 * hash) + getNodesInfoList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.flippers.messages.MessageProtos.Message parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.flippers.messages.MessageProtos.Message parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.flippers.messages.MessageProtos.Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.flippers.messages.MessageProtos.Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.flippers.messages.MessageProtos.Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.flippers.messages.MessageProtos.Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.flippers.messages.MessageProtos.Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.flippers.messages.MessageProtos.Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.flippers.messages.MessageProtos.Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.flippers.messages.MessageProtos.Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.flippers.messages.MessageProtos.Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.flippers.messages.MessageProtos.Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.flippers.messages.MessageProtos.Message prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code messages.Message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:messages.Message)
        org.flippers.messages.MessageProtos.MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.flippers.messages.MessageProtos.internal_static_messages_Message_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.flippers.messages.MessageProtos.internal_static_messages_Message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.flippers.messages.MessageProtos.Message.class, org.flippers.messages.MessageProtos.Message.Builder.class);
      }

      // Construct using org.flippers.messages.MessageProtos.Message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getNodesInfoFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        type_ = 0;

        sequenceNumber_ = "";

        if (senderBuilder_ == null) {
          sender_ = null;
        } else {
          sender_ = null;
          senderBuilder_ = null;
        }
        if (nodesInfoBuilder_ == null) {
          nodesInfo_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          nodesInfoBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.flippers.messages.MessageProtos.internal_static_messages_Message_descriptor;
      }

      @java.lang.Override
      public org.flippers.messages.MessageProtos.Message getDefaultInstanceForType() {
        return org.flippers.messages.MessageProtos.Message.getDefaultInstance();
      }

      @java.lang.Override
      public org.flippers.messages.MessageProtos.Message build() {
        org.flippers.messages.MessageProtos.Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.flippers.messages.MessageProtos.Message buildPartial() {
        org.flippers.messages.MessageProtos.Message result = new org.flippers.messages.MessageProtos.Message(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.type_ = type_;
        result.sequenceNumber_ = sequenceNumber_;
        if (senderBuilder_ == null) {
          result.sender_ = sender_;
        } else {
          result.sender_ = senderBuilder_.build();
        }
        if (nodesInfoBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            nodesInfo_ = java.util.Collections.unmodifiableList(nodesInfo_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.nodesInfo_ = nodesInfo_;
        } else {
          result.nodesInfo_ = nodesInfoBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.flippers.messages.MessageProtos.Message) {
          return mergeFrom((org.flippers.messages.MessageProtos.Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.flippers.messages.MessageProtos.Message other) {
        if (other == org.flippers.messages.MessageProtos.Message.getDefaultInstance()) return this;
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (!other.getSequenceNumber().isEmpty()) {
          sequenceNumber_ = other.sequenceNumber_;
          onChanged();
        }
        if (other.hasSender()) {
          mergeSender(other.getSender());
        }
        if (nodesInfoBuilder_ == null) {
          if (!other.nodesInfo_.isEmpty()) {
            if (nodesInfo_.isEmpty()) {
              nodesInfo_ = other.nodesInfo_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureNodesInfoIsMutable();
              nodesInfo_.addAll(other.nodesInfo_);
            }
            onChanged();
          }
        } else {
          if (!other.nodesInfo_.isEmpty()) {
            if (nodesInfoBuilder_.isEmpty()) {
              nodesInfoBuilder_.dispose();
              nodesInfoBuilder_ = null;
              nodesInfo_ = other.nodesInfo_;
              bitField0_ = (bitField0_ & ~0x00000008);
              nodesInfoBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getNodesInfoFieldBuilder() : null;
            } else {
              nodesInfoBuilder_.addAllMessages(other.nodesInfo_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.flippers.messages.MessageProtos.Message parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.flippers.messages.MessageProtos.Message) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int type_ = 0;
      /**
       * <code>.messages.Message.MessageType type = 1;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.messages.Message.MessageType type = 1;</code>
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.messages.Message.MessageType type = 1;</code>
       */
      public org.flippers.messages.MessageProtos.Message.MessageType getType() {
        @SuppressWarnings("deprecation")
        org.flippers.messages.MessageProtos.Message.MessageType result = org.flippers.messages.MessageProtos.Message.MessageType.valueOf(type_);
        return result == null ? org.flippers.messages.MessageProtos.Message.MessageType.UNRECOGNIZED : result;
      }
      /**
       * <code>.messages.Message.MessageType type = 1;</code>
       */
      public Builder setType(org.flippers.messages.MessageProtos.Message.MessageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.messages.Message.MessageType type = 1;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object sequenceNumber_ = "";
      /**
       * <code>string sequenceNumber = 3;</code>
       */
      public java.lang.String getSequenceNumber() {
        java.lang.Object ref = sequenceNumber_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sequenceNumber_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string sequenceNumber = 3;</code>
       */
      public com.google.protobuf.ByteString
          getSequenceNumberBytes() {
        java.lang.Object ref = sequenceNumber_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sequenceNumber_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string sequenceNumber = 3;</code>
       */
      public Builder setSequenceNumber(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sequenceNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string sequenceNumber = 3;</code>
       */
      public Builder clearSequenceNumber() {
        
        sequenceNumber_ = getDefaultInstance().getSequenceNumber();
        onChanged();
        return this;
      }
      /**
       * <code>string sequenceNumber = 3;</code>
       */
      public Builder setSequenceNumberBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        sequenceNumber_ = value;
        onChanged();
        return this;
      }

      private org.flippers.messages.MessageProtos.NodeInfo sender_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          org.flippers.messages.MessageProtos.NodeInfo, org.flippers.messages.MessageProtos.NodeInfo.Builder, org.flippers.messages.MessageProtos.NodeInfoOrBuilder> senderBuilder_;
      /**
       * <code>.messages.NodeInfo sender = 4;</code>
       */
      public boolean hasSender() {
        return senderBuilder_ != null || sender_ != null;
      }
      /**
       * <code>.messages.NodeInfo sender = 4;</code>
       */
      public org.flippers.messages.MessageProtos.NodeInfo getSender() {
        if (senderBuilder_ == null) {
          return sender_ == null ? org.flippers.messages.MessageProtos.NodeInfo.getDefaultInstance() : sender_;
        } else {
          return senderBuilder_.getMessage();
        }
      }
      /**
       * <code>.messages.NodeInfo sender = 4;</code>
       */
      public Builder setSender(org.flippers.messages.MessageProtos.NodeInfo value) {
        if (senderBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          sender_ = value;
          onChanged();
        } else {
          senderBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.messages.NodeInfo sender = 4;</code>
       */
      public Builder setSender(
          org.flippers.messages.MessageProtos.NodeInfo.Builder builderForValue) {
        if (senderBuilder_ == null) {
          sender_ = builderForValue.build();
          onChanged();
        } else {
          senderBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.messages.NodeInfo sender = 4;</code>
       */
      public Builder mergeSender(org.flippers.messages.MessageProtos.NodeInfo value) {
        if (senderBuilder_ == null) {
          if (sender_ != null) {
            sender_ =
              org.flippers.messages.MessageProtos.NodeInfo.newBuilder(sender_).mergeFrom(value).buildPartial();
          } else {
            sender_ = value;
          }
          onChanged();
        } else {
          senderBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.messages.NodeInfo sender = 4;</code>
       */
      public Builder clearSender() {
        if (senderBuilder_ == null) {
          sender_ = null;
          onChanged();
        } else {
          sender_ = null;
          senderBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.messages.NodeInfo sender = 4;</code>
       */
      public org.flippers.messages.MessageProtos.NodeInfo.Builder getSenderBuilder() {
        
        onChanged();
        return getSenderFieldBuilder().getBuilder();
      }
      /**
       * <code>.messages.NodeInfo sender = 4;</code>
       */
      public org.flippers.messages.MessageProtos.NodeInfoOrBuilder getSenderOrBuilder() {
        if (senderBuilder_ != null) {
          return senderBuilder_.getMessageOrBuilder();
        } else {
          return sender_ == null ?
              org.flippers.messages.MessageProtos.NodeInfo.getDefaultInstance() : sender_;
        }
      }
      /**
       * <code>.messages.NodeInfo sender = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          org.flippers.messages.MessageProtos.NodeInfo, org.flippers.messages.MessageProtos.NodeInfo.Builder, org.flippers.messages.MessageProtos.NodeInfoOrBuilder> 
          getSenderFieldBuilder() {
        if (senderBuilder_ == null) {
          senderBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              org.flippers.messages.MessageProtos.NodeInfo, org.flippers.messages.MessageProtos.NodeInfo.Builder, org.flippers.messages.MessageProtos.NodeInfoOrBuilder>(
                  getSender(),
                  getParentForChildren(),
                  isClean());
          sender_ = null;
        }
        return senderBuilder_;
      }

      private java.util.List<org.flippers.messages.MessageProtos.NodeInfo> nodesInfo_ =
        java.util.Collections.emptyList();
      private void ensureNodesInfoIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          nodesInfo_ = new java.util.ArrayList<org.flippers.messages.MessageProtos.NodeInfo>(nodesInfo_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.flippers.messages.MessageProtos.NodeInfo, org.flippers.messages.MessageProtos.NodeInfo.Builder, org.flippers.messages.MessageProtos.NodeInfoOrBuilder> nodesInfoBuilder_;

      /**
       * <code>repeated .messages.NodeInfo nodesInfo = 5;</code>
       */
      public java.util.List<org.flippers.messages.MessageProtos.NodeInfo> getNodesInfoList() {
        if (nodesInfoBuilder_ == null) {
          return java.util.Collections.unmodifiableList(nodesInfo_);
        } else {
          return nodesInfoBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .messages.NodeInfo nodesInfo = 5;</code>
       */
      public int getNodesInfoCount() {
        if (nodesInfoBuilder_ == null) {
          return nodesInfo_.size();
        } else {
          return nodesInfoBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .messages.NodeInfo nodesInfo = 5;</code>
       */
      public org.flippers.messages.MessageProtos.NodeInfo getNodesInfo(int index) {
        if (nodesInfoBuilder_ == null) {
          return nodesInfo_.get(index);
        } else {
          return nodesInfoBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .messages.NodeInfo nodesInfo = 5;</code>
       */
      public Builder setNodesInfo(
          int index, org.flippers.messages.MessageProtos.NodeInfo value) {
        if (nodesInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNodesInfoIsMutable();
          nodesInfo_.set(index, value);
          onChanged();
        } else {
          nodesInfoBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .messages.NodeInfo nodesInfo = 5;</code>
       */
      public Builder setNodesInfo(
          int index, org.flippers.messages.MessageProtos.NodeInfo.Builder builderForValue) {
        if (nodesInfoBuilder_ == null) {
          ensureNodesInfoIsMutable();
          nodesInfo_.set(index, builderForValue.build());
          onChanged();
        } else {
          nodesInfoBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .messages.NodeInfo nodesInfo = 5;</code>
       */
      public Builder addNodesInfo(org.flippers.messages.MessageProtos.NodeInfo value) {
        if (nodesInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNodesInfoIsMutable();
          nodesInfo_.add(value);
          onChanged();
        } else {
          nodesInfoBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .messages.NodeInfo nodesInfo = 5;</code>
       */
      public Builder addNodesInfo(
          int index, org.flippers.messages.MessageProtos.NodeInfo value) {
        if (nodesInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNodesInfoIsMutable();
          nodesInfo_.add(index, value);
          onChanged();
        } else {
          nodesInfoBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .messages.NodeInfo nodesInfo = 5;</code>
       */
      public Builder addNodesInfo(
          org.flippers.messages.MessageProtos.NodeInfo.Builder builderForValue) {
        if (nodesInfoBuilder_ == null) {
          ensureNodesInfoIsMutable();
          nodesInfo_.add(builderForValue.build());
          onChanged();
        } else {
          nodesInfoBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .messages.NodeInfo nodesInfo = 5;</code>
       */
      public Builder addNodesInfo(
          int index, org.flippers.messages.MessageProtos.NodeInfo.Builder builderForValue) {
        if (nodesInfoBuilder_ == null) {
          ensureNodesInfoIsMutable();
          nodesInfo_.add(index, builderForValue.build());
          onChanged();
        } else {
          nodesInfoBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .messages.NodeInfo nodesInfo = 5;</code>
       */
      public Builder addAllNodesInfo(
          java.lang.Iterable<? extends org.flippers.messages.MessageProtos.NodeInfo> values) {
        if (nodesInfoBuilder_ == null) {
          ensureNodesInfoIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, nodesInfo_);
          onChanged();
        } else {
          nodesInfoBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .messages.NodeInfo nodesInfo = 5;</code>
       */
      public Builder clearNodesInfo() {
        if (nodesInfoBuilder_ == null) {
          nodesInfo_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          nodesInfoBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .messages.NodeInfo nodesInfo = 5;</code>
       */
      public Builder removeNodesInfo(int index) {
        if (nodesInfoBuilder_ == null) {
          ensureNodesInfoIsMutable();
          nodesInfo_.remove(index);
          onChanged();
        } else {
          nodesInfoBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .messages.NodeInfo nodesInfo = 5;</code>
       */
      public org.flippers.messages.MessageProtos.NodeInfo.Builder getNodesInfoBuilder(
          int index) {
        return getNodesInfoFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .messages.NodeInfo nodesInfo = 5;</code>
       */
      public org.flippers.messages.MessageProtos.NodeInfoOrBuilder getNodesInfoOrBuilder(
          int index) {
        if (nodesInfoBuilder_ == null) {
          return nodesInfo_.get(index);  } else {
          return nodesInfoBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .messages.NodeInfo nodesInfo = 5;</code>
       */
      public java.util.List<? extends org.flippers.messages.MessageProtos.NodeInfoOrBuilder> 
           getNodesInfoOrBuilderList() {
        if (nodesInfoBuilder_ != null) {
          return nodesInfoBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(nodesInfo_);
        }
      }
      /**
       * <code>repeated .messages.NodeInfo nodesInfo = 5;</code>
       */
      public org.flippers.messages.MessageProtos.NodeInfo.Builder addNodesInfoBuilder() {
        return getNodesInfoFieldBuilder().addBuilder(
            org.flippers.messages.MessageProtos.NodeInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .messages.NodeInfo nodesInfo = 5;</code>
       */
      public org.flippers.messages.MessageProtos.NodeInfo.Builder addNodesInfoBuilder(
          int index) {
        return getNodesInfoFieldBuilder().addBuilder(
            index, org.flippers.messages.MessageProtos.NodeInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .messages.NodeInfo nodesInfo = 5;</code>
       */
      public java.util.List<org.flippers.messages.MessageProtos.NodeInfo.Builder> 
           getNodesInfoBuilderList() {
        return getNodesInfoFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.flippers.messages.MessageProtos.NodeInfo, org.flippers.messages.MessageProtos.NodeInfo.Builder, org.flippers.messages.MessageProtos.NodeInfoOrBuilder> 
          getNodesInfoFieldBuilder() {
        if (nodesInfoBuilder_ == null) {
          nodesInfoBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              org.flippers.messages.MessageProtos.NodeInfo, org.flippers.messages.MessageProtos.NodeInfo.Builder, org.flippers.messages.MessageProtos.NodeInfoOrBuilder>(
                  nodesInfo_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          nodesInfo_ = null;
        }
        return nodesInfoBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:messages.Message)
    }

    // @@protoc_insertion_point(class_scope:messages.Message)
    private static final org.flippers.messages.MessageProtos.Message DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.flippers.messages.MessageProtos.Message();
    }

    public static org.flippers.messages.MessageProtos.Message getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Message>
        PARSER = new com.google.protobuf.AbstractParser<Message>() {
      @java.lang.Override
      public Message parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Message(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Message> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Message> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.flippers.messages.MessageProtos.Message getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface NodeInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:messages.NodeInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string ipAddress = 1;</code>
     */
    java.lang.String getIpAddress();
    /**
     * <code>string ipAddress = 1;</code>
     */
    com.google.protobuf.ByteString
        getIpAddressBytes();

    /**
     * <code>string nodeId = 2;</code>
     */
    java.lang.String getNodeId();
    /**
     * <code>string nodeId = 2;</code>
     */
    com.google.protobuf.ByteString
        getNodeIdBytes();

    /**
     * <code>int32 port = 3;</code>
     */
    int getPort();

    /**
     * <code>.messages.NodeInfo.InfoType type = 4;</code>
     */
    int getTypeValue();
    /**
     * <code>.messages.NodeInfo.InfoType type = 4;</code>
     */
    org.flippers.messages.MessageProtos.NodeInfo.InfoType getType();
  }
  /**
   * Protobuf type {@code messages.NodeInfo}
   */
  public  static final class NodeInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:messages.NodeInfo)
      NodeInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use NodeInfo.newBuilder() to construct.
    private NodeInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private NodeInfo() {
      ipAddress_ = "";
      nodeId_ = "";
      port_ = 0;
      type_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private NodeInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              ipAddress_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              nodeId_ = s;
              break;
            }
            case 24: {

              port_ = input.readInt32();
              break;
            }
            case 32: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.flippers.messages.MessageProtos.internal_static_messages_NodeInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.flippers.messages.MessageProtos.internal_static_messages_NodeInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.flippers.messages.MessageProtos.NodeInfo.class, org.flippers.messages.MessageProtos.NodeInfo.Builder.class);
    }

    /**
     * Protobuf enum {@code messages.NodeInfo.InfoType}
     */
    public enum InfoType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>ALIVE = 0;</code>
       */
      ALIVE(0),
      /**
       * <code>JOINED = 1;</code>
       */
      JOINED(1),
      /**
       * <code>SUSPECT = 2;</code>
       */
      SUSPECT(2),
      /**
       * <code>DEAD = 3;</code>
       */
      DEAD(3),
      /**
       * <code>LEFT = 4;</code>
       */
      LEFT(4),
      /**
       * <code>MEMBER = 5;</code>
       */
      MEMBER(5),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>ALIVE = 0;</code>
       */
      public static final int ALIVE_VALUE = 0;
      /**
       * <code>JOINED = 1;</code>
       */
      public static final int JOINED_VALUE = 1;
      /**
       * <code>SUSPECT = 2;</code>
       */
      public static final int SUSPECT_VALUE = 2;
      /**
       * <code>DEAD = 3;</code>
       */
      public static final int DEAD_VALUE = 3;
      /**
       * <code>LEFT = 4;</code>
       */
      public static final int LEFT_VALUE = 4;
      /**
       * <code>MEMBER = 5;</code>
       */
      public static final int MEMBER_VALUE = 5;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static InfoType valueOf(int value) {
        return forNumber(value);
      }

      public static InfoType forNumber(int value) {
        switch (value) {
          case 0: return ALIVE;
          case 1: return JOINED;
          case 2: return SUSPECT;
          case 3: return DEAD;
          case 4: return LEFT;
          case 5: return MEMBER;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<InfoType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          InfoType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<InfoType>() {
              public InfoType findValueByNumber(int number) {
                return InfoType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.flippers.messages.MessageProtos.NodeInfo.getDescriptor().getEnumTypes().get(0);
      }

      private static final InfoType[] VALUES = values();

      public static InfoType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private InfoType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:messages.NodeInfo.InfoType)
    }

    public static final int IPADDRESS_FIELD_NUMBER = 1;
    private volatile java.lang.Object ipAddress_;
    /**
     * <code>string ipAddress = 1;</code>
     */
    public java.lang.String getIpAddress() {
      java.lang.Object ref = ipAddress_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ipAddress_ = s;
        return s;
      }
    }
    /**
     * <code>string ipAddress = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIpAddressBytes() {
      java.lang.Object ref = ipAddress_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ipAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NODEID_FIELD_NUMBER = 2;
    private volatile java.lang.Object nodeId_;
    /**
     * <code>string nodeId = 2;</code>
     */
    public java.lang.String getNodeId() {
      java.lang.Object ref = nodeId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nodeId_ = s;
        return s;
      }
    }
    /**
     * <code>string nodeId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNodeIdBytes() {
      java.lang.Object ref = nodeId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nodeId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PORT_FIELD_NUMBER = 3;
    private int port_;
    /**
     * <code>int32 port = 3;</code>
     */
    public int getPort() {
      return port_;
    }

    public static final int TYPE_FIELD_NUMBER = 4;
    private int type_;
    /**
     * <code>.messages.NodeInfo.InfoType type = 4;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.messages.NodeInfo.InfoType type = 4;</code>
     */
    public org.flippers.messages.MessageProtos.NodeInfo.InfoType getType() {
      @SuppressWarnings("deprecation")
      org.flippers.messages.MessageProtos.NodeInfo.InfoType result = org.flippers.messages.MessageProtos.NodeInfo.InfoType.valueOf(type_);
      return result == null ? org.flippers.messages.MessageProtos.NodeInfo.InfoType.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIpAddressBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, ipAddress_);
      }
      if (!getNodeIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, nodeId_);
      }
      if (port_ != 0) {
        output.writeInt32(3, port_);
      }
      if (type_ != org.flippers.messages.MessageProtos.NodeInfo.InfoType.ALIVE.getNumber()) {
        output.writeEnum(4, type_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIpAddressBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, ipAddress_);
      }
      if (!getNodeIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, nodeId_);
      }
      if (port_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, port_);
      }
      if (type_ != org.flippers.messages.MessageProtos.NodeInfo.InfoType.ALIVE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, type_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.flippers.messages.MessageProtos.NodeInfo)) {
        return super.equals(obj);
      }
      org.flippers.messages.MessageProtos.NodeInfo other = (org.flippers.messages.MessageProtos.NodeInfo) obj;

      boolean result = true;
      result = result && getIpAddress()
          .equals(other.getIpAddress());
      result = result && getNodeId()
          .equals(other.getNodeId());
      result = result && (getPort()
          == other.getPort());
      result = result && type_ == other.type_;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + IPADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getIpAddress().hashCode();
      hash = (37 * hash) + NODEID_FIELD_NUMBER;
      hash = (53 * hash) + getNodeId().hashCode();
      hash = (37 * hash) + PORT_FIELD_NUMBER;
      hash = (53 * hash) + getPort();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.flippers.messages.MessageProtos.NodeInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.flippers.messages.MessageProtos.NodeInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.flippers.messages.MessageProtos.NodeInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.flippers.messages.MessageProtos.NodeInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.flippers.messages.MessageProtos.NodeInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.flippers.messages.MessageProtos.NodeInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.flippers.messages.MessageProtos.NodeInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.flippers.messages.MessageProtos.NodeInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.flippers.messages.MessageProtos.NodeInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.flippers.messages.MessageProtos.NodeInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.flippers.messages.MessageProtos.NodeInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.flippers.messages.MessageProtos.NodeInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.flippers.messages.MessageProtos.NodeInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code messages.NodeInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:messages.NodeInfo)
        org.flippers.messages.MessageProtos.NodeInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.flippers.messages.MessageProtos.internal_static_messages_NodeInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.flippers.messages.MessageProtos.internal_static_messages_NodeInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.flippers.messages.MessageProtos.NodeInfo.class, org.flippers.messages.MessageProtos.NodeInfo.Builder.class);
      }

      // Construct using org.flippers.messages.MessageProtos.NodeInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        ipAddress_ = "";

        nodeId_ = "";

        port_ = 0;

        type_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.flippers.messages.MessageProtos.internal_static_messages_NodeInfo_descriptor;
      }

      @java.lang.Override
      public org.flippers.messages.MessageProtos.NodeInfo getDefaultInstanceForType() {
        return org.flippers.messages.MessageProtos.NodeInfo.getDefaultInstance();
      }

      @java.lang.Override
      public org.flippers.messages.MessageProtos.NodeInfo build() {
        org.flippers.messages.MessageProtos.NodeInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.flippers.messages.MessageProtos.NodeInfo buildPartial() {
        org.flippers.messages.MessageProtos.NodeInfo result = new org.flippers.messages.MessageProtos.NodeInfo(this);
        result.ipAddress_ = ipAddress_;
        result.nodeId_ = nodeId_;
        result.port_ = port_;
        result.type_ = type_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.flippers.messages.MessageProtos.NodeInfo) {
          return mergeFrom((org.flippers.messages.MessageProtos.NodeInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.flippers.messages.MessageProtos.NodeInfo other) {
        if (other == org.flippers.messages.MessageProtos.NodeInfo.getDefaultInstance()) return this;
        if (!other.getIpAddress().isEmpty()) {
          ipAddress_ = other.ipAddress_;
          onChanged();
        }
        if (!other.getNodeId().isEmpty()) {
          nodeId_ = other.nodeId_;
          onChanged();
        }
        if (other.getPort() != 0) {
          setPort(other.getPort());
        }
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.flippers.messages.MessageProtos.NodeInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.flippers.messages.MessageProtos.NodeInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object ipAddress_ = "";
      /**
       * <code>string ipAddress = 1;</code>
       */
      public java.lang.String getIpAddress() {
        java.lang.Object ref = ipAddress_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          ipAddress_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string ipAddress = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIpAddressBytes() {
        java.lang.Object ref = ipAddress_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ipAddress_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string ipAddress = 1;</code>
       */
      public Builder setIpAddress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        ipAddress_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string ipAddress = 1;</code>
       */
      public Builder clearIpAddress() {
        
        ipAddress_ = getDefaultInstance().getIpAddress();
        onChanged();
        return this;
      }
      /**
       * <code>string ipAddress = 1;</code>
       */
      public Builder setIpAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        ipAddress_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object nodeId_ = "";
      /**
       * <code>string nodeId = 2;</code>
       */
      public java.lang.String getNodeId() {
        java.lang.Object ref = nodeId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          nodeId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string nodeId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNodeIdBytes() {
        java.lang.Object ref = nodeId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nodeId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string nodeId = 2;</code>
       */
      public Builder setNodeId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        nodeId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string nodeId = 2;</code>
       */
      public Builder clearNodeId() {
        
        nodeId_ = getDefaultInstance().getNodeId();
        onChanged();
        return this;
      }
      /**
       * <code>string nodeId = 2;</code>
       */
      public Builder setNodeIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        nodeId_ = value;
        onChanged();
        return this;
      }

      private int port_ ;
      /**
       * <code>int32 port = 3;</code>
       */
      public int getPort() {
        return port_;
      }
      /**
       * <code>int32 port = 3;</code>
       */
      public Builder setPort(int value) {
        
        port_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 port = 3;</code>
       */
      public Builder clearPort() {
        
        port_ = 0;
        onChanged();
        return this;
      }

      private int type_ = 0;
      /**
       * <code>.messages.NodeInfo.InfoType type = 4;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.messages.NodeInfo.InfoType type = 4;</code>
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.messages.NodeInfo.InfoType type = 4;</code>
       */
      public org.flippers.messages.MessageProtos.NodeInfo.InfoType getType() {
        @SuppressWarnings("deprecation")
        org.flippers.messages.MessageProtos.NodeInfo.InfoType result = org.flippers.messages.MessageProtos.NodeInfo.InfoType.valueOf(type_);
        return result == null ? org.flippers.messages.MessageProtos.NodeInfo.InfoType.UNRECOGNIZED : result;
      }
      /**
       * <code>.messages.NodeInfo.InfoType type = 4;</code>
       */
      public Builder setType(org.flippers.messages.MessageProtos.NodeInfo.InfoType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.messages.NodeInfo.InfoType type = 4;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:messages.NodeInfo)
    }

    // @@protoc_insertion_point(class_scope:messages.NodeInfo)
    private static final org.flippers.messages.MessageProtos.NodeInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.flippers.messages.MessageProtos.NodeInfo();
    }

    public static org.flippers.messages.MessageProtos.NodeInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<NodeInfo>
        PARSER = new com.google.protobuf.AbstractParser<NodeInfo>() {
      @java.lang.Override
      public NodeInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new NodeInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<NodeInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<NodeInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.flippers.messages.MessageProtos.NodeInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_messages_Message_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_messages_Message_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_messages_NodeInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_messages_NodeInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rmessage.proto\022\010messages\"\337\001\n\007Message\022+\n" +
      "\004type\030\001 \001(\0162\035.messages.Message.MessageTy" +
      "pe\022\026\n\016sequenceNumber\030\003 \001(\t\022\"\n\006sender\030\004 \001" +
      "(\0132\022.messages.NodeInfo\022%\n\tnodesInfo\030\005 \003(" +
      "\0132\022.messages.NodeInfo\"D\n\013MessageType\022\010\n\004" +
      "PING\020\000\022\007\n\003ACK\020\001\022\r\n\tPING_NODE\020\002\022\010\n\004JOIN\020\003" +
      "\022\t\n\005LEAVE\020\004\"\266\001\n\010NodeInfo\022\021\n\tipAddress\030\001 " +
      "\001(\t\022\016\n\006nodeId\030\002 \001(\t\022\014\n\004port\030\003 \001(\005\022)\n\004typ" +
      "e\030\004 \001(\0162\033.messages.NodeInfo.InfoType\"N\n\010" +
      "InfoType\022\t\n\005ALIVE\020\000\022\n\n\006JOINED\020\001\022\013\n\007SUSPE" +
      "CT\020\002\022\010\n\004DEAD\020\003\022\010\n\004LEFT\020\004\022\n\n\006MEMBER\020\005B&\n\025" +
      "org.flippers.messagesB\rMessageProtosb\006pr" +
      "oto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_messages_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_messages_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_messages_Message_descriptor,
        new java.lang.String[] { "Type", "SequenceNumber", "Sender", "NodesInfo", });
    internal_static_messages_NodeInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_messages_NodeInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_messages_NodeInfo_descriptor,
        new java.lang.String[] { "IpAddress", "NodeId", "Port", "Type", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
